SELECT STARNAME
FROM STARSIN
WHERE MOVIETITLE = 'The usual Suspects'
INTERSECT
SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'm';

SELECT STARNAME
FROM STARSIN, MOVIE
WHERE MOVIEYEAR=1995 AND 
STARSIN.MOVIETITLE=MOVIE.TITLE
AND MOVIE.STUDIONAME='MGM';

SELECT DISTINCT NAME 
FROM MOVIE, MOVIEEXEC
WHERE MOVIE.STUDIONAME = 'MGM' AND MOVIEEXEC.CERT# = MOVIE.PRODUCERC#; 

SELECT TITLE
FROM MOVIE
WHERE LENGTH > (SELECT LENGTH FROM MOVIE WHERE TITLE='Star Wars');

SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME = 'Stephen Spielberg');
