SELECT SHIPS.NAME
FROM SHIPS
WHERE SHIPS.CLASS = (SELECT CLASS FROM CLASSES WHERE DISPLACEMENT > 50000);

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS
FROM SHIPS, CLASSES, OUTCOMES, BATTLES
WHERE BATTLES.NAME = 'Guadalcanal' AND
OUTCOMES.SHIP = SHIPS.NAME AND 
SHIPS.CLASS = CLASSES.CLASS AND
OUTCOMES.BATTLE = BATTLES.NAME;

SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE TYPE = 'bb'

INTERSECT

SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE TYPE = 'bc';

SELECT SHIP
FROM OUTCOMES
WHERE RESULT = 'damaged'

INTERSECT 

SELECT SHIP
FROM OUTCOMES
WHERE RESULT = 'ok';
