SELECT PRODUCT.MAKER, LAPTOP.SPEED
FROM PRODUCT, LAPTOP
WHERE PRODUCT.type='laptop' AND
LAPTOP.MODEL = PRODUCT.MODEL AND
LAPTOP.HD > 9;

SELECT PRODUCT.MODEL, PC.PRICE
FROM PRODUCT, PC
WHERE PRODUCT.model = PC.MODEL AND 
PRODUCT.type = 'pc' AND 
PRODUCT.MAKER = 'B'

UNION

SELECT PRODUCT.MODEL, PRINTER.PRICE
FROM PRODUCT, PRINTER
WHERE PRODUCT.model = PRINTER.MODEL AND 
PRODUCT.type = 'printer' AND 
PRODUCT.MAKER = 'B'

UNION

SELECT PRODUCT.MODEL, LAPTOP.PRICE
FROM PRODUCT, LAPTOP
WHERE PRODUCT.model = LAPTOP.MODEL AND 
PRODUCT.type = 'laptop' AND 
PRODUCT.MAKER = 'B';

SELECT DISTINCT MAKER
FROM PRODUCT
WHERE TYPE='laptop'

EXCEPT

SELECT DISTINCT MAKER
FROM PRODUCT
WHERE TYPE='pc';

SELECT DISTINCT PC1.HD
FROM PC AS PC1, PC AS PC2
WHERE PC1.CODE != PC2.CODE AND PC1.HD = PC2.HD;

SELECT DISTINCT PC1.MODEL, PC2.MODEL
FROM PC as PC1, PC AS PC2
WHERE PC1.SPEED = PC2.SPEED AND PC1.RAM = PC2.RAM AND 
PC1.MODEL != PC2.MODEL AND 
PC1.MODEL < PC2.MODEL;

SELECT DISTINCT P1.MAKER
FROM PRODUCT AS P1, PRODUCT AS P2, PC AS PC1, PC AS PC2
WHERE PC1.CODE != PC2.CODE AND
PC1.SPEED >= 400 AND PC2.SPEED >= 400 AND
P1.MODEL = PC1.MODEL AND
P2.MODEL = PC2.MODEL AND 
P1.MAKER = P2.MAKER;
