SELECT MOVIESTAR.NAME
FROM MOVIE, STARSIN, MOVIESTAR
WHERE MOVIE.TITLE = 'The Usual Suspects' AND
STARSIN.MOVIETITLE = 'The Usual Suspects' AND
MOVIESTAR.NAME = STARSIN.STARNAME AND 
MOVIESTAR.GENDER = 'M';

SELECT STARSIN.STARNAME
FROM MOVIE, STARSIN
WHERE MOVIE.STUDIONAME = 'MGM' AND 
MOVIE.YEAR = 1995 AND
STARSIN.MOVIETITLE = MOVIE.TITLE;

SELECT DISTINCT MOVIEEXEC.NAME
FROM MOVIE, MOVIEEXEC
WHERE STUDIONAME = 'MGM' AND
MOVIEEXEC.CERT# = MOVIE.PRODUCERC#;

SELECT M.TITLE
FROM MOVIE AS M, MOVIE AS FICTIVE
WHERE FICTIVE.TITLE = 'STAR WARS' AND
M.LENGTH > FICTIVE.LENGTH;

SELECT M.NAME
FROM MOVIEEXEC AS M, MOVIEEXEC AS FICTIVE
WHERE FICTIVE.NAME = 'Stephen Spielberg' AND
M.NETWORTH > FICTIVE.NETWORTH;
