SELECT MODEL, HD AS MHz, RAM AS GB
FROM PC
WHERE PRICE < 1200;

SELECT DISTINCT MAKER
FROM PRODUCT 
WHERE TYPE = 'Printer';

SELECT MODEL, RAM, SCREEN
FROM LAPTOP
WHERE PRICE > 1000;

SELECT *
FROM PRINTER
WHERE COLOR = 'y';

SELECT MODEL, HD, RAM
FROM PC
WHERE (CD = '12x' OR CD = '16x' ) AND PRICE < 2000;
