SELECT MOVIESTAR.NAME
FROM MOVIESTAR
WHERE MOVIESTAR.NAME IN (SELECT MOVIEEXEC.NAME FROM MOVIEEXEC WHERE MOVIEEXEC.NETWORTH > 10000000);

SELECT MOVIESTAR.NAME
FROM MOVIESTAR

EXCEPT

SELECT MOVIESTAR.NAME
FROM MOVIESTAR
WHERE MOVIESTAR.NAME IN (SELECT MOVIEEXEC.NAME FROM MOVIEEXEC);

SELECT DISTINCT M2.TITLE
FROM MOVIE AS M1, MOVIE AS M2
WHERE M1.TITLE = 'Star Wars' AND M1.LENGTH < M2.LENGTH;

SELECT M.TITLE, P.NAME 
FROM MOVIEEXEC AS P, MOVIEEXEC AS FICTIVE, MOVIE AS M
WHERE FICTIVE.NAME = 'Merv Griffin' AND
P.NETWORTH > FICTIVE.NETWORTH AND
P.CERT# = M.PRODUCERC#;
