SELECT DISTINCT P.MAKER
FROM PRODUCT AS P, PC AS FICTIVE
WHERE P.TYPE = 'PC' AND
FICTIVE.MODEL = P.MODEL AND
FICTIVE.SPEED > 500;

SELECT CODE, MODEL, PRICE
FROM PRINTER
WHERE PRICE >= ALL(SELECT PRICE FROM PRINTER);

SELECT *
FROM LAPTOP
WHERE SPEED < ALL(SELECT SPEED FROM PC);

SELECT TBL.MODEL, TBL.PRICE
FROM ((SELECT MODEL, PRICE FROM PC) UNION
(SELECT MODEL, PRICE FROM PRINTER) UNION
(SELECT MODEL, PRICE FROM LAPTOP)) AS TBL
WHERE TBL.PRICE>=ALL(SELECT PRICE FROM ((SELECT MODEL, PRICE FROM PC)
UNION (SELECT MODEL, PRICE FROM PRINTER) UNION
(SELECT MODEL, PRICE FROM LAPTOP)) AS TBL2)

SELECT P.MAKER
FROM PRODUCT AS P, PRINTER AS FICTIVE
WHERE FICTIVE.COLOR = 'y' AND
FICTIVE.PRICE < ANY(SELECT PRICE FROM PRINTER WHERE COLOR='y') AND
P.TYPE = 'printer' AND
P.MODEL = FICTIVE.MODEL;

SELECT DISTINCT P.MAKER
FROM PRODUCT AS P, PC AS FICTIVE1, PC AS FICTIVE2
WHERE FICTIVE1.RAM < ANY(SELECT RAM FROM PC) AND
FICTIVE2.SPEED > ANY(SELECT SPEED FROM PC) AND
FICTIVE1.CODE = FICTIVE2.CODE AND
P.TYPE = 'PC' AND P.MODEL = FICTIVE1.MODEL;
